# Generated by Django 4.2.4 on 2023-09-02 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aexercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('reps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aexercises.exercise')),
                ('set1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aexercises.set')),
            ],
        ),
    ]
