# Generated by Django 4.2.4 on 2023-09-02 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aexercises', '0002_set_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='id',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='set1',
        ),
        migrations.AddField(
            model_name='workout',
            name='set_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aexercises.set'),
            preserve_default=False,
        ),
    ]
