# Generated by Django 4.2.4 on 2023-09-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aexercises', '0003_remove_workout_id_remove_workout_set1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='set_ptr',
        ),
        migrations.AddField(
            model_name='workout',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.ManyToManyField(to='aexercises.set'),
        ),
    ]
